global:
  scrape_interval: 15s
rule_files:
  - "./isc_alert_rules.yml"
scrape_configs:
  - job_name: 'iris'
    metrics_path: /api/monitor/metrics
    static_configs:
      - targets: 
        - 'host.docker.internal:881'
    scheme: http
  - job_name: 'interop_metrics'
    metrics_path: /api/monitor/interop/interfaces
    static_configs:
      - targets:
          - 'host.docker.internal:881'
    scheme: http
  # - job_name: 'custom_iris_metrics'
  #   metrics_path: /custom/monitor/metrics
  #   static_configs:
  #     - targets:
  #         - 'host.docker.internal:881'
  #   basic_auth:
  #     username: '_SYSTEM'
  #     password: 'SYS'

